apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: house-model
  namespace: kserve
spec:
  predictor:
    minReplicas: 0
    model:
      modelFormat:
        name: sklearn
      storageUri: pvc://kserve-model-pvc