apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kserve-model-pvc
  namespace: kserve
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath